name: "Contagious Action"
description: "List container images and tags"
inputs:
  contagious_version:
    description: "Version of contagious"
    required: false
    default: "0.1.2"
  registry:
    description: "Name of container registry"
    required: true
    default: ""
outputs:
  images:
    description: ""
    value: ${{ steps.contagious.outputs.images }}
runs:
  using: "composite"
  steps:
    - name: Docker run contagious action
      id: contagious
      shell: bash
      run: |
        socket="/var/run/docker.sock"
        images=$(docker run \
          --mount type=bind,source=${socket},target=/var/run/docker.sock \
          --mount type=bind,source=${HOME}/.docker/config.json,target=/root/.docker/config.json \
          -e GITHUB_OUTPUT \
          ghcr.io/duffney/contagious-action:v${{ inputs.contagious_version }} \
          list ${{ inputs.registry }} --next-tag --output json)
        images=$(echo "$images" | jq -c -r @json)
        echo "images=$images" >> $GITHUB_OUTPUT
