on: [push]

jobs:
  setup_matrix:
    runs-on: ubuntu-latest
    name: Local Test
    outputs:
      images: ${{ steps.contagious.outputs.images }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Contagious
        uses: ./ # Uses an action in the root directory
        id: contagious
        with:
          contagious_version: "0.1.2"
          registry: "ghcr.io/duffney"
          next-tag: "true"
  matrix:
    runs-on: ubuntu-latest
    needs: setup_matrix
    strategy:
      matrix:
        inclued: ${{fromJson(needs.setup_matrix.outputs.images)}}
    steps:
      - name: CurrentTag
        run: |
          CURRENT_TAG="${{ matrix.current_tag}}"
          echo  "current tag is: $CURRENT_TAG"
      - name: NextTag
        run: |
          NEXT_TAG="${{ matrix.next_tag}}"
          echo  "Next tag will be: $NEXT_TAG"
