on: [push]

jobs:
  setup_matrix:
    runs-on: ubuntu-latest
    name: Local Test
    outputs:
      images: ${{ steps.contagious.outputs.images }}
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Contagious
        uses: ./ # Uses an action in the root directory
        id: contagious
        with:
          contagious_version: "0.1.2"
          registry: "ghcr.io/duffney"
          next-tag: "true"
      - name: debug output
        run: |
          echo "Raw output: ${{ steps.contagious.outputs.images }}"
          echo '${{ steps.contagious.outputs.images }}'
  matrix:
    runs-on: ubuntu-latest
    needs: setup_matrix
    name: Matrix Test
    steps:
      - name: debug matrix output
        run: |
          echo "Raw output: ${{ steps.setup_matrix.outputs.images}}"
          echo '${{ steps.setup_matrix.outputs.images}}'
